### ISSUE TITLE
پاک نشدن رکوردهای قبلی

### ISSUE THREAD

**Issue by mh292929** [vfarid/cf-replace-ips#1]
من این اسکریپت رو ۲ بار ران کردم اما متاسفانه فقط رکورد اضافه میشه اما قبلیها پاک نمیشه. مثلا اگه ۲ بار لیست آیپی ۲۰ تایی به اسکریپت بدیم ۴۰ رکورد ایجاد میشه

**Comment by vfarid** [comment]
احتمالا پکیج jq نصب نبوده. با اسکریپت اسکنر پایتون که بعدتر نوشتم فکر کنم دیگه نیاز به این کد نباشه
